#python python/SKFlat.py -a NonIso -e 2016a -i SingleMuon -n 50 --batchname auto &
#python python/SKFlat.py -a NonIso -e 2016a -i DYJets -n 50 --batchname auto &
#python python/SKFlat.py -a NonIso -e 2016a -i WJets_MG -n 50 --batchname auto &
#python python/SKFlat.py -a NonIso -e 2016a -i TTLL_powheg -n 50 --batchname auto &
#python python/SKFlat.py -a NonIso -e 2016a -i TTLJ_powheg -n 50 --batchname auto &
#python python/SKFlat.py -a NonIso -e 2016a -i WW_pythia -n 50 --batchname auto &
#python python/SKFlat.py -a NonIso -e 2016a -i WWTo2L2Nu_powheg -n 50 --batchname auto &
#python python/SKFlat.py -a NonIso -e 2016a -i WZ_pythia -n 50 --batchname auto &
#python python/SKFlat.py -a NonIso -e 2016a -i WZTo3LNu_mllmin4p0_powheg -n 50 --batchname auto &

python python/SKFlat.py -a NonIso -e 2016b -i SingleMuon -n 50 --batchname auto &
python python/SKFlat.py -a NonIso -e 2016b -i DYJets -n 50 --batchname auto &
python python/SKFlat.py -a NonIso -e 2016b -i WJets_MG -n 50 --batchname auto &
python python/SKFlat.py -a NonIso -e 2016b -i TTLL_powheg -n 50 --batchname auto &
python python/SKFlat.py -a NonIso -e 2016b -i TTLJ_powheg -n 50 --batchname auto &
python python/SKFlat.py -a NonIso -e 2016b -i WW_pythia -n 50 --batchname auto &
python python/SKFlat.py -a NonIso -e 2016b -i WWTo2L2Nu_powheg -n 50 --batchname auto &
python python/SKFlat.py -a NonIso -e 2016b -i WZ_pythia -n 50 --batchname auto &
python python/SKFlat.py -a NonIso -e 2016b -i WZTo3LNu_mllmin4p0_powheg -n 50 --batchname auto &
