SKFlat.py -a GetEffLumi -e 2016preVFP -i WtoLNtoLNuHtoLNuBB_InverseHeavyN-Mu_MN1000_TuneCP5_13TeV-amcatnlo-pythia8 -n 1 &
SKFlat.py -a GetEffLumi -e 2016preVFP -i WtoLNtoLNuHtoLNuBB_InverseHeavyN-Mu_MN1100_TuneCP5_13TeV-amcatnlo-pythia8 -n 1 &
SKFlat.py -a GetEffLumi -e 2016preVFP -i WtoLNtoLNuHtoLNuBB_InverseHeavyN-Mu_MN1200_TuneCP5_13TeV-amcatnlo-pythia8 -n 1 &
SKFlat.py -a GetEffLumi -e 2016preVFP -i WtoLNtoLNuHtoLNuBB_InverseHeavyN-Mu_MN500_TuneCP5_13TeV-amcatnlo-pythia8 -n 1 &
SKFlat.py -a GetEffLumi -e 2016preVFP -i WtoLNtoLNuHtoLNuBB_InverseHeavyN-Mu_MN600_TuneCP5_13TeV-amcatnlo-pythia8 -n 1 &
SKFlat.py -a GetEffLumi -e 2016preVFP -i WtoLNtoLNuHtoLNuBB_InverseHeavyN-Mu_MN700_TuneCP5_13TeV-amcatnlo-pythia8 -n 1 &
SKFlat.py -a GetEffLumi -e 2016preVFP -i WtoLNtoLNuHtoLNuBB_InverseHeavyN-Mu_MN800_TuneCP5_13TeV-amcatnlo-pythia8 -n 1 &
SKFlat.py -a GetEffLumi -e 2016preVFP -i WtoLNtoLNuHtoLNuBB_InverseHeavyN-Mu_MN900_TuneCP5_13TeV-amcatnlo-pythia8 -n 1 &
SKFlat.py -a GetEffLumi -e 2016preVFP -i WtoLNtoLNuHtoLNuBB_VBF_InverseHeavyN-Mu_MN1000_TuneCP5_13TeV-amcatnlo-pythia8 -n 1 &
SKFlat.py -a GetEffLumi -e 2016preVFP -i WtoLNtoLNuHtoLNuBB_VBF_InverseHeavyN-Mu_MN1100_TuneCP5_13TeV-amcatnlo-pythia8 -n 1 &
SKFlat.py -a GetEffLumi -e 2016preVFP -i WtoLNtoLNuHtoLNuBB_VBF_InverseHeavyN-Mu_MN1200_TuneCP5_13TeV-amcatnlo-pythia8 -n 1 &
SKFlat.py -a GetEffLumi -e 2016preVFP -i WtoLNtoLNuHtoLNuBB_VBF_InverseHeavyN-Mu_MN500_TuneCP5_13TeV-amcatnlo-pythia8 -n 1 &
SKFlat.py -a GetEffLumi -e 2016preVFP -i WtoLNtoLNuHtoLNuBB_VBF_InverseHeavyN-Mu_MN600_TuneCP5_13TeV-amcatnlo-pythia8 -n 1 &
SKFlat.py -a GetEffLumi -e 2016preVFP -i WtoLNtoLNuHtoLNuBB_VBF_InverseHeavyN-Mu_MN700_TuneCP5_13TeV-amcatnlo-pythia8 -n 1 &
SKFlat.py -a GetEffLumi -e 2016preVFP -i WtoLNtoLNuHtoLNuBB_VBF_InverseHeavyN-Mu_MN800_TuneCP5_13TeV-amcatnlo-pythia8 -n 1 &
SKFlat.py -a GetEffLumi -e 2016preVFP -i WtoLNtoLNuHtoLNuBB_VBF_InverseHeavyN-Mu_MN900_TuneCP5_13TeV-amcatnlo-pythia8 -n 1 &
SKFlat.py -a GetEffLumi -e 2016preVFP -i WtoLNtoLNuZtoLNuBB_InverseHeavyN-Mu_MN1000_TuneCP5_13TeV-amcatnlo-pythia8 -n 1 &
SKFlat.py -a GetEffLumi -e 2016preVFP -i WtoLNtoLNuZtoLNuBB_InverseHeavyN-Mu_MN1100_TuneCP5_13TeV-amcatnlo-pythia8 -n 1 &
SKFlat.py -a GetEffLumi -e 2016preVFP -i WtoLNtoLNuZtoLNuBB_InverseHeavyN-Mu_MN1200_TuneCP5_13TeV-amcatnlo-pythia8 -n 1 &
SKFlat.py -a GetEffLumi -e 2016preVFP -i WtoLNtoLNuZtoLNuBB_InverseHeavyN-Mu_MN500_TuneCP5_13TeV-amcatnlo-pythia8 -n 1 &
SKFlat.py -a GetEffLumi -e 2016preVFP -i WtoLNtoLNuZtoLNuBB_InverseHeavyN-Mu_MN600_TuneCP5_13TeV-amcatnlo-pythia8 -n 1 &
SKFlat.py -a GetEffLumi -e 2016preVFP -i WtoLNtoLNuZtoLNuBB_InverseHeavyN-Mu_MN700_TuneCP5_13TeV-amcatnlo-pythia8 -n 1 &
SKFlat.py -a GetEffLumi -e 2016preVFP -i WtoLNtoLNuZtoLNuBB_InverseHeavyN-Mu_MN800_TuneCP5_13TeV-amcatnlo-pythia8 -n 1 &
SKFlat.py -a GetEffLumi -e 2016preVFP -i WtoLNtoLNuZtoLNuBB_InverseHeavyN-Mu_MN900_TuneCP5_13TeV-amcatnlo-pythia8 -n 1 &
SKFlat.py -a GetEffLumi -e 2016preVFP -i WtoLNtoLNuZtoLNuBB_VBF_InverseHeavyN-Mu_MN1000_TuneCP5_13TeV-amcatnlo-pythia8 -n 1 &
SKFlat.py -a GetEffLumi -e 2016preVFP -i WtoLNtoLNuZtoLNuBB_VBF_InverseHeavyN-Mu_MN1100_TuneCP5_13TeV-amcatnlo-pythia8 -n 1 &
SKFlat.py -a GetEffLumi -e 2016preVFP -i WtoLNtoLNuZtoLNuBB_VBF_InverseHeavyN-Mu_MN1200_TuneCP5_13TeV-amcatnlo-pythia8 -n 1 &
SKFlat.py -a GetEffLumi -e 2016preVFP -i WtoLNtoLNuZtoLNuBB_VBF_InverseHeavyN-Mu_MN500_TuneCP5_13TeV-amcatnlo-pythia8 -n 1 &
SKFlat.py -a GetEffLumi -e 2016preVFP -i WtoLNtoLNuZtoLNuBB_VBF_InverseHeavyN-Mu_MN600_TuneCP5_13TeV-amcatnlo-pythia8 -n 1 &
SKFlat.py -a GetEffLumi -e 2016preVFP -i WtoLNtoLNuZtoLNuBB_VBF_InverseHeavyN-Mu_MN700_TuneCP5_13TeV-amcatnlo-pythia8 -n 1 &
SKFlat.py -a GetEffLumi -e 2016preVFP -i WtoLNtoLNuZtoLNuBB_VBF_InverseHeavyN-Mu_MN800_TuneCP5_13TeV-amcatnlo-pythia8 -n 1 &
SKFlat.py -a GetEffLumi -e 2016preVFP -i WtoLNtoLNuZtoLNuBB_VBF_InverseHeavyN-Mu_MN900_TuneCP5_13TeV-amcatnlo-pythia8 -n 1 &

SKFlat.py -a GetEffLumi -e 2016postVFP -i WtoLNtoLNuHtoLNuBB_InverseHeavyN-Mu_MN1000_TuneCP5_13TeV-amcatnlo-pythia8 -n 1 &
SKFlat.py -a GetEffLumi -e 2016postVFP -i WtoLNtoLNuHtoLNuBB_InverseHeavyN-Mu_MN1100_TuneCP5_13TeV-amcatnlo-pythia8 -n 1 &
SKFlat.py -a GetEffLumi -e 2016postVFP -i WtoLNtoLNuHtoLNuBB_InverseHeavyN-Mu_MN1200_TuneCP5_13TeV-amcatnlo-pythia8 -n 1 &
SKFlat.py -a GetEffLumi -e 2016postVFP -i WtoLNtoLNuHtoLNuBB_InverseHeavyN-Mu_MN500_TuneCP5_13TeV-amcatnlo-pythia8 -n 1 &
SKFlat.py -a GetEffLumi -e 2016postVFP -i WtoLNtoLNuHtoLNuBB_InverseHeavyN-Mu_MN600_TuneCP5_13TeV-amcatnlo-pythia8 -n 1 &
SKFlat.py -a GetEffLumi -e 2016postVFP -i WtoLNtoLNuHtoLNuBB_InverseHeavyN-Mu_MN700_TuneCP5_13TeV-amcatnlo-pythia8 -n 1 &
SKFlat.py -a GetEffLumi -e 2016postVFP -i WtoLNtoLNuHtoLNuBB_InverseHeavyN-Mu_MN800_TuneCP5_13TeV-amcatnlo-pythia8 -n 1 &
SKFlat.py -a GetEffLumi -e 2016postVFP -i WtoLNtoLNuHtoLNuBB_InverseHeavyN-Mu_MN900_TuneCP5_13TeV-amcatnlo-pythia8 -n 1 &
SKFlat.py -a GetEffLumi -e 2016postVFP -i WtoLNtoLNuHtoLNuBB_VBF_InverseHeavyN-Mu_MN1000_TuneCP5_13TeV-amcatnlo-pythia8 -n 1 &
SKFlat.py -a GetEffLumi -e 2016postVFP -i WtoLNtoLNuHtoLNuBB_VBF_InverseHeavyN-Mu_MN1100_TuneCP5_13TeV-amcatnlo-pythia8 -n 1 &
SKFlat.py -a GetEffLumi -e 2016postVFP -i WtoLNtoLNuHtoLNuBB_VBF_InverseHeavyN-Mu_MN1200_TuneCP5_13TeV-amcatnlo-pythia8 -n 1 &
SKFlat.py -a GetEffLumi -e 2016postVFP -i WtoLNtoLNuHtoLNuBB_VBF_InverseHeavyN-Mu_MN500_TuneCP5_13TeV-amcatnlo-pythia8 -n 1 &
SKFlat.py -a GetEffLumi -e 2016postVFP -i WtoLNtoLNuHtoLNuBB_VBF_InverseHeavyN-Mu_MN600_TuneCP5_13TeV-amcatnlo-pythia8 -n 1 &
SKFlat.py -a GetEffLumi -e 2016postVFP -i WtoLNtoLNuHtoLNuBB_VBF_InverseHeavyN-Mu_MN700_TuneCP5_13TeV-amcatnlo-pythia8 -n 1 &
SKFlat.py -a GetEffLumi -e 2016postVFP -i WtoLNtoLNuHtoLNuBB_VBF_InverseHeavyN-Mu_MN800_TuneCP5_13TeV-amcatnlo-pythia8 -n 1 &
SKFlat.py -a GetEffLumi -e 2016postVFP -i WtoLNtoLNuHtoLNuBB_VBF_InverseHeavyN-Mu_MN900_TuneCP5_13TeV-amcatnlo-pythia8 -n 1 &
SKFlat.py -a GetEffLumi -e 2016postVFP -i WtoLNtoLNuZtoLNuBB_InverseHeavyN-Mu_MN1000_TuneCP5_13TeV-amcatnlo-pythia8 -n 1 &
SKFlat.py -a GetEffLumi -e 2016postVFP -i WtoLNtoLNuZtoLNuBB_InverseHeavyN-Mu_MN1100_TuneCP5_13TeV-amcatnlo-pythia8 -n 1 &
SKFlat.py -a GetEffLumi -e 2016postVFP -i WtoLNtoLNuZtoLNuBB_InverseHeavyN-Mu_MN1200_TuneCP5_13TeV-amcatnlo-pythia8 -n 1 &
SKFlat.py -a GetEffLumi -e 2016postVFP -i WtoLNtoLNuZtoLNuBB_InverseHeavyN-Mu_MN500_TuneCP5_13TeV-amcatnlo-pythia8 -n 1 &
SKFlat.py -a GetEffLumi -e 2016postVFP -i WtoLNtoLNuZtoLNuBB_InverseHeavyN-Mu_MN600_TuneCP5_13TeV-amcatnlo-pythia8 -n 1 &
SKFlat.py -a GetEffLumi -e 2016postVFP -i WtoLNtoLNuZtoLNuBB_InverseHeavyN-Mu_MN700_TuneCP5_13TeV-amcatnlo-pythia8 -n 1 &
SKFlat.py -a GetEffLumi -e 2016postVFP -i WtoLNtoLNuZtoLNuBB_InverseHeavyN-Mu_MN800_TuneCP5_13TeV-amcatnlo-pythia8 -n 1 &
SKFlat.py -a GetEffLumi -e 2016postVFP -i WtoLNtoLNuZtoLNuBB_InverseHeavyN-Mu_MN900_TuneCP5_13TeV-amcatnlo-pythia8 -n 1 &
SKFlat.py -a GetEffLumi -e 2016postVFP -i WtoLNtoLNuZtoLNuBB_VBF_InverseHeavyN-Mu_MN1000_TuneCP5_13TeV-amcatnlo-pythia8 -n 1 &
SKFlat.py -a GetEffLumi -e 2016postVFP -i WtoLNtoLNuZtoLNuBB_VBF_InverseHeavyN-Mu_MN1100_TuneCP5_13TeV-amcatnlo-pythia8 -n 1 &
SKFlat.py -a GetEffLumi -e 2016postVFP -i WtoLNtoLNuZtoLNuBB_VBF_InverseHeavyN-Mu_MN1200_TuneCP5_13TeV-amcatnlo-pythia8 -n 1 &
SKFlat.py -a GetEffLumi -e 2016postVFP -i WtoLNtoLNuZtoLNuBB_VBF_InverseHeavyN-Mu_MN500_TuneCP5_13TeV-amcatnlo-pythia8 -n 1 &
SKFlat.py -a GetEffLumi -e 2016postVFP -i WtoLNtoLNuZtoLNuBB_VBF_InverseHeavyN-Mu_MN600_TuneCP5_13TeV-amcatnlo-pythia8 -n 1 &
SKFlat.py -a GetEffLumi -e 2016postVFP -i WtoLNtoLNuZtoLNuBB_VBF_InverseHeavyN-Mu_MN700_TuneCP5_13TeV-amcatnlo-pythia8 -n 1 &
SKFlat.py -a GetEffLumi -e 2016postVFP -i WtoLNtoLNuZtoLNuBB_VBF_InverseHeavyN-Mu_MN800_TuneCP5_13TeV-amcatnlo-pythia8 -n 1 &
SKFlat.py -a GetEffLumi -e 2016postVFP -i WtoLNtoLNuZtoLNuBB_VBF_InverseHeavyN-Mu_MN900_TuneCP5_13TeV-amcatnlo-pythia8 -n 1 &
