source SubmitTopPtScripts/2018/submitTT.sh
sleept 30
source SubmitTopPtScripts/2018/submitDY.sh
sleep 30
source SubmitTopPtScripts/2018/submitDATA.sh
source SubmitTopPtScripts/2018/submitQCD.sh
source SubmitTopPtScripts/2018/submitT.sh
source SubmitTopPtScripts/2018/submitVV.sh
source SubmitTopPtScripts/2018/submitW.sh
source SubmitTopPtScripts/2018/submitOTHERS.sh
