SKFlat.py -a singlelepton_analysis --skim SkimTree_SingleLepton -e 2016preVFP -i QCD_Pt-120To170_MuEnriched -n 5 &
SKFlat.py -a singlelepton_analysis --skim SkimTree_SingleLepton -e 2016preVFP -i QCD_Pt-120to170_EMEnriched -n 1 &
SKFlat.py -a singlelepton_analysis --skim SkimTree_SingleLepton -e 2016preVFP -i QCD_Pt-15To20_MuEnriched -n 1 &
SKFlat.py -a singlelepton_analysis --skim SkimTree_SingleLepton -e 2016preVFP -i QCD_Pt-15to20_EMEnriched -n 1 &
SKFlat.py -a singlelepton_analysis --skim SkimTree_SingleLepton -e 2016preVFP -i QCD_Pt-170To300_MuEnriched -n 10 &
SKFlat.py -a singlelepton_analysis --skim SkimTree_SingleLepton -e 2016preVFP -i QCD_Pt-170to300_EMEnriched -n 1 &
SKFlat.py -a singlelepton_analysis --skim SkimTree_SingleLepton -e 2016preVFP -i QCD_Pt-20To30_MuEnriched -n 1 &
SKFlat.py -a singlelepton_analysis --skim SkimTree_SingleLepton -e 2016preVFP -i QCD_Pt-20to30_EMEnriched -n 1 &
SKFlat.py -a singlelepton_analysis --skim SkimTree_SingleLepton -e 2016preVFP -i QCD_Pt-300To470_MuEnriched -n 10 &
SKFlat.py -a singlelepton_analysis --skim SkimTree_SingleLepton -e 2016preVFP -i QCD_Pt-300toInf_EMEnriched -n 1 &
SKFlat.py -a singlelepton_analysis --skim SkimTree_SingleLepton -e 2016preVFP -i QCD_Pt-30To50_MuEnriched -n 1 &
SKFlat.py -a singlelepton_analysis --skim SkimTree_SingleLepton -e 2016preVFP -i QCD_Pt-30to50_EMEnriched -n 1 &
SKFlat.py -a singlelepton_analysis --skim SkimTree_SingleLepton -e 2016preVFP -i QCD_Pt-470To600_MuEnriched -n 10 &
SKFlat.py -a singlelepton_analysis --skim SkimTree_SingleLepton -e 2016preVFP -i QCD_Pt-50To80_MuEnriched -n 1 &
SKFlat.py -a singlelepton_analysis --skim SkimTree_SingleLepton -e 2016preVFP -i QCD_Pt-50to80_EMEnriched -n 1 &
SKFlat.py -a singlelepton_analysis --skim SkimTree_SingleLepton -e 2016preVFP -i QCD_Pt-600To800_MuEnriched -n 10 &
SKFlat.py -a singlelepton_analysis --skim SkimTree_SingleLepton -e 2016preVFP -i QCD_Pt-800To1000_MuEnriched -n 10 &
SKFlat.py -a singlelepton_analysis --skim SkimTree_SingleLepton -e 2016preVFP -i QCD_Pt-80To120_MuEnriched -n 1 &
SKFlat.py -a singlelepton_analysis --skim SkimTree_SingleLepton -e 2016preVFP -i QCD_Pt-80to120_EMEnriched -n 1 &

